//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinesEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int ID { get; set; }
        public int IdProducto { get; set; }
        public int Cantidad { get; set; }
        public decimal Importe { get; set; }
        public decimal Pago { get; set; }
        public decimal Cambio { get; set; }
        public decimal Total { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
